version: '3'
services:


  ### MySQL database for inventory
  db-inventory:
    container_name: db-inventory
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
     MYSQL_DATABASE: ms_inventory
     MYSQL_USER: sa
     MYSQL_PASSWORD: 123321
     MYSQL_ROOT_PASSWORD: 123321
    ports:
      - 3306:3306
    expose:
      - 3306

  ### Postgres database for Products
  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123321
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432