version: '3'
services:
  ### Postgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123321
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123321
      MYSQL_ROOT_PASSWORD: 123321
    ports:
      - 3336:3336
    expose:
      - 3336

  ### Postgres database for Products
  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123321
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432